function re=est(beta,gamma0,gamma1,n)
    [Z,X,delta]=data(beta,gamma0,gamma1,n);
    death_number=sum(delta);
    death_time=X.*delta;
    death_time=sort(death_time(death_time>0));
    mindeathX=min(X,death_time(death_number));
    ST=((repmat(X,1,death_number))>=(repmat(death_time',n,1)));
    S2T=((repmat(X,1,death_number))<(repmat(death_time',n,1))).*((repmat(X,1,death_number))>(repmat([0;death_time(1:death_number-1)]',n,1)));
    STK=(X<=death_time(death_number));
    Lambda_posi=sum(repmat(X',death_number,1)>=repmat(death_time,1,n));
    Lambda_posi=Lambda_posi+1;
    Lambda_temp=zeros(death_number+1,1);
    beta_temp=0.5;
    gamma0_temp=1;
    gamma1_temp=-1;
    Lambda_est=fLambda(Z,death_time,death_number,ST,S2T,beta_temp,gamma0_temp,gamma1_temp,X);
    beta_est=fbeta(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,mindeathX,STK);
    gamma_est=fgamma(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,beta_est,STK);
    gamma_est=gamma_est';
    diff1=max(abs(Lambda_est-Lambda_temp));
    diff2=sqrt(sum(([gamma_est;beta_est]-[gamma0_temp;gamma1_temp;beta_temp]).^2));
    iter=0;
    while(((diff2>1e-3)||(diff1>1e-3))&&(iter<=100))
    Lambda_temp=Lambda_est;
    beta_temp=beta_est;
    gamma0_temp=gamma_est(1);
    gamma1_temp=gamma_est(2);
    Lambda_est=fLambda(Z,death_time,death_number,ST,S2T,beta_temp,gamma0_temp,gamma1_temp,X);
    beta_est=fbeta(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,mindeathX,STK);
    gamma_est=fgamma(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,beta_est,STK);
    gamma_est=gamma_est';
    diff1=max(abs(Lambda_est-Lambda_temp));
    diff2=sqrt(sum(([gamma_est;beta_est]-[gamma0_temp;gamma1_temp;beta_temp]).^2));
    iter=iter+1;
    iter
    end
    while(iter>100)
    [Z,X,delta]=data(beta,gamma0,gamma1,n);    
    death_number=sum(delta);
    death_time=X.*delta;
    death_time=sort(death_time(death_time>0));
    mindeathX=min(X,death_time(death_number));
    ST=((repmat(X,1,death_number))>=(repmat(death_time',n,1)));
    S2T=((repmat(X,1,death_number))<(repmat(death_time',n,1))).*((repmat(X,1,death_number))>(repmat([0;death_time(1:death_number-1)]',n,1)));
    STK=(X<=death_time(death_number));
    Lambda_posi=sum(repmat(X',death_number,1)>=repmat(death_time,1,n));
    Lambda_posi=Lambda_posi+1;
    Lambda_temp=zeros(death_number+1,1);
    beta_temp=0.5;
    gamma0_temp=1;
    gamma1_temp=-1;
    Lambda_est=fLambda(Z,death_time,death_number,ST,S2T,beta_temp,gamma0_temp,gamma1_temp,X);
    beta_est=fbeta(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,mindeathX,STK);
    gamma_est=fgamma(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,beta_est,STK);
    gamma_est=gamma_est';
    diff1=max(abs(Lambda_est-Lambda_temp));
    diff2=sqrt(sum(([gamma_est;beta_est]-[gamma0_temp;gamma1_temp;beta_temp]).^2));
    iter=0;
    while(((diff2>1e-3)||(diff1>1e-3))&&(iter<=100))
    Lambda_temp=Lambda_est;
    beta_temp=beta_est;
    gamma0_temp=gamma_est(1);
    gamma1_temp=gamma_est(2);
    Lambda_est=fLambda(Z,death_time,death_number,ST,S2T,beta_temp,gamma0_temp,gamma1_temp,X);
    beta_est=fbeta(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,mindeathX,STK);
    gamma_est=fgamma(Z,X,delta,Lambda_est,Lambda_posi,gamma0_temp,gamma1_temp,beta_est,STK);
    gamma_est=gamma_est';
    diff1=max(abs(Lambda_est-Lambda_temp));
    diff2=sqrt(sum(([gamma_est;beta_est]-[gamma0_temp;gamma1_temp;beta_temp]).^2));
    iter=iter+1;
    iter
    end
    end
    re=zeros(death_number+5+n*4+sum(delta),1);
    re(1)=beta_est;
    re(2)=gamma_est(1);
    re(3)=gamma_est(2);
    re(4)=death_number;
    re(5:death_number+5)=Lambda_est;
    re(death_number+6:death_number+5+n)=Z;
    re(death_number+6+n:death_number+5+n*2)=X;
    re(death_number+6+n*2:death_number+5+n*3)=delta;
    re(death_number+6+n*3:death_number+5+n*4)=Lambda_posi;
    re(death_number+6+n*4:death_number+5+n*4+sum(delta))=death_time;
        
    
    %{
    betaest=beta_est;
    gamma0est=gamma_est(1);
    gamma1est=gamma_est(2);
    Lambdaest=Lambda_est';
    %}